<?xml version="1.0"?>
<!--
  Author: Massimiliano Pandolfo

  Version 0.3.1
  The new macro sphere_inertia_macro improves the creation of auxiliary spheres.
-->

<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Properties -->
  <xacro:property name="cable_length" value="0.7" /> <!-- [m] -->
  <xacro:property name="cable_radius" value="0.005" /> <!-- [m] -->
  <xacro:property name="cable_mass" value="0.05" /> <!-- [kg] -->
  <xacro:property name="sphere_radius" value="0.005" /> <!-- [m] -->
  <xacro:property name="sphere_mass" value="0.001" /> <!-- [kg] -->


  <!-- Macro for the auxiliary spheres -->
  <xacro:macro name="sphere_macro" params="r mass">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
        <inertia
        ixx="${0.4 * mass * r * r}" ixy="0.0" ixz="0.0"
        iyy="${0.4 * mass * r * r}" iyz="0.0"
        izz="${0.4 * mass * r * r}"/>
    </inertial>
    <visual>
      <geometry>
        <sphere radius="${r}"/>
      </geometry>
    </visual>
  </xacro:macro>


  <!-- Connecting the cable to a UAV -->
  <xacro:macro name="cable_macro"
    params="robot_namespace uav_body_frame id_number">


    <!-- The CABLE is represented as a cylindrical link -->
    <link name="${robot_namespace}/cable_${id_number}">

      <!-- ############### RANDOM INERTIA. just for testing!!! ############### -->
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${cable_mass}"/>
        <inertia
          ixx="1.0" ixy="0.0" ixz="0.0"
          iyy="1.0" iyz="0.0"
          izz="1.0"/>
      </inertial>
      <!-- ###################### end of RANDOM INERTIA. ##################### -->

      <visual>
        <geometry>
          <cylinder length="${cable_length}" radius="${cable_radius}"/>
        </geometry>
      </visual>

    </link>


    <!-- The sphere is needed to implement a double revolute joint -->
    <link name="${robot_namespace}/aux_sphere_${id_number}">
      <xacro:sphere_macro r="${sphere_radius}" mass="${sphere_mass}"/>
    </link>


    <!-- First revolute joint, connecting the CABLE to the auxiliary sphere -->
    <joint name="${robot_namespace}/joint_cab${id_number}aux${id_number}" type="continuous"> <!-- revolute w/o limits to the angle -->

      <!-- Placing the joint on the upper end of the cable -->
      <origin xyz="0 0 ${cable_length/2}" rpy="0 0 0" />

      <!-- Axis in the CHILD REFERENCE FRAME around which the rotation happens -->
      <axis xyz="1 0 0" />

      <parent link="${robot_namespace}/cable_${id_number}" />
      <child link="${robot_namespace}/aux_sphere_${id_number}" />
    </joint>


    <!-- Second revolute joint, connecting the UAV to the auxiliary sphere -->
    <joint name="${robot_namespace}/joint_aux${id_number}uav${id_number}" type="continuous"> <!-- revolute w/o limits to the angle -->

      <!-- Here I can specify the origin of the joint in the UAV body frame -->
      <origin xyz="0 0 0" rpy="0 0 0" />

      <!-- Axis in the CHILD REFERENCE FRAME around which the rotation happens -->
      <axis xyz="0 1 0" />

      <parent link="${robot_namespace}/aux_sphere_${id_number}" />
      <child link="${uav_body_frame}" />
      <!--
      <parent link="${uav_body_frame}" />
      <child link="${robot_namespace}/aux_sphere_${id_number}" />
      -->
    </joint>

  </xacro:macro>
</robot>

<!--
<origin xyz="0 ${arm_length} ${rotor_offset_top}" rpy="0 0 0" />
-->