<?xml version="1.0"?>
<!--
  Author: Massimiliano Pandolfo

  Version 0.5.1
  Changed approach to the problem, now cable_macro handles ALL the auxiliary spheres.
  ADDITIONAL TESTING REQUIRED to make sure the various offsets are correct.
-->

<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Properties -->
  <xacro:property name="cable_length" value="0.7" /> <!-- [m] -->
  <xacro:property name="cable_radius" value="0.005" /> <!-- [m] -->
  <xacro:property name="cable_mass" value="0.05" /> <!-- [kg] -->
  <xacro:property name="sphere_radius" value="0.005" /> <!-- [m] -->
  <xacro:property name="sphere_mass" value="0.001" /> <!-- [kg] -->

  <!-- TEST macro for a box -->
  <xacro:macro name="cuboid_macro">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1"/>
        <inertia
        ixx="1" ixy="0.0" ixz="0.0"
        iyy="1" iyz="0.0"
        izz="1"/>
    </inertial>
    <visual>
      <geometry>
        <box size=".1 .2 .01"/>
      </geometry>
    </visual>
  </xacro:macro>

  <!-- Macro for the auxiliary spheres -->
  <xacro:macro name="sphere_macro" params="r mass">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
        <inertia
        ixx="${0.4 * mass * r * r}" ixy="0.0" ixz="0.0"
        iyy="${0.4 * mass * r * r}" iyz="0.0"
        izz="${0.4 * mass * r * r}"/>
    </inertial>
    <visual>
      <geometry>
        <sphere radius="${r}"/>
      </geometry>
    </visual>
  </xacro:macro>


  <!-- Macro that connects a cable to a UAV -->
  <xacro:macro name="cable_macro"
    params="robot_namespace uav_body_frame id_number">

    <!-- This sphere is between payload (root node) and cable -->
    <link name="${robot_namespace}/aux_pay_${id_number}">
      <xacro:sphere_macro r="${sphere_radius}" mass="${sphere_mass}"/>
      <!--xacro:cuboid_macro/> for testing -->
    </link>

    <!-- The CABLE is represented as a cylindrical link -->
    <link name="${robot_namespace}/cable_${id_number}">
      <!-- ############### RANDOM INERTIA. just for testing!!! ############### -->
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${cable_mass}"/>
        <inertia
          ixx="1.0" ixy="0.0" ixz="0.0"
          iyy="1.0" iyz="0.0"
          izz="1.0"/>
      </inertial>
      <!-- ###################### end of RANDOM INERTIA. ##################### -->
      <visual>
         <origin xyz="0 0 ${cable_length/2}" rpy="0 0 0"/> <!-- ATTENZIONE -->
        <geometry>
          <cylinder length="${cable_length}" radius="${cable_radius}"/>
        </geometry>
      </visual>
    </link>

    <!-- This sphere is between cable and uav -->
    <link name="${robot_namespace}/aux_uav_${id_number}">
      <xacro:sphere_macro r="${sphere_radius}" mass="${sphere_mass}"/>
    </link>


    <!-- Joint between payload sphere and the cable -->
    <joint name="${robot_namespace}/joint_sph_cab_${id_number}" type="continuous">

      <!-- Placing the joint ref frame in the center of the sphere -->
      <origin xyz="0 0 0" rpy="0 0 0" />

      <!-- Axis in the CHILD REFERENCE FRAME around which the rotation happens -->
      <axis xyz="1 0 0" />

      <parent link="${robot_namespace}/aux_pay_${id_number}" />
      <child link="${robot_namespace}/cable_${id_number}" />

    </joint>


    <!-- Joint between the cable and the UAV sphere -->
    <joint name="${robot_namespace}/joint_cab_sph_${id_number}" type="continuous">

      <!-- Placing the joint ref frame on the upper end of the cable -->
      <origin xyz="0 0 ${cable_length}" rpy="0 0 0" />

      <!-- Axis in the CHILD REFERENCE FRAME around which the rotation happens -->
      <axis xyz="1 0 0" />

      <parent link="${robot_namespace}/cable_${id_number}" />
      <child link="${robot_namespace}/aux_uav_${id_number}" />

    </joint>


    <!-- Joint between the UAV sphere amd the UAV-->
    <joint name="${robot_namespace}/joint_sph_uav_${id_number}" type="continuous">

      <!-- Placing the joint ref frame in the center of the sphere -->
      <origin xyz="0 0 0" rpy="0 0 0" />

      <!-- Axis in the CHILD REFERENCE FRAME around which the rotation happens -->
      <axis xyz="0 1 0" />

      <parent link="${robot_namespace}/aux_uav_${id_number}" />
      <child link="${uav_body_frame}" />
    </joint>

  </xacro:macro>


</robot>