<?xml version="1.0"?>
<!--
  Author: Massimiliano Pandolfo

  Version 0.7
  payload_macro now receives two links as input, and acts as root node for the robot tree.
  With the exception of some minor improvements, this is supposed to be the final version before 1.0.
-->

<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Properties -->
  <xacro:property name="cable_length" value="0.7" /> <!-- [m] -->
  <xacro:property name="cable_radius" value="0.005" /> <!-- [m] -->
  <xacro:property name="cable_mass" value="0.05" /> <!-- [kg] -->
  <xacro:property name="sphere_radius" value="0.005" /> <!-- [m] -->
  <xacro:property name="sphere_mass" value="0.001" /> <!-- [kg] -->
  <xacro:property name="x_payload" value="1"/> <!-- [m] -->
  <xacro:property name="y_payload" value="0.01"/> <!-- [m] -->
  <xacro:property name="z_payload" value="0.01"/> <!-- [m] -->
  <xacro:property name="payload_mass" value="1"/> <!-- [kg] -->


  <!-- Macro that creates a cuboid -->
  <xacro:macro name="cuboid_macro" params="x y z mass">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
        <inertia
        ixx="${mass*(y*y+z*z)/12}" ixy="0.0" ixz="0.0"
        iyy="${mass*(x*x+z*z)/12}" iyz="0.0"
        izz="${mass*(y*y+x*x)/12}"/>
    </inertial>
    <visual>
      <geometry>
        <box size="${x} ${y} ${z}"/>
      </geometry>
    </visual>
  </xacro:macro>


  <!-- Macro for the auxiliary spheres -->
  <xacro:macro name="sphere_macro" params="r mass">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
        <inertia
        ixx="${0.4 * mass * r * r}" ixy="0.0" ixz="0.0"
        iyy="${0.4 * mass * r * r}" iyz="0.0"
        izz="${0.4 * mass * r * r}"/>
    </inertial>
    <visual>
      <geometry>
        <sphere radius="${r}"/>
      </geometry>
    </visual>
  </xacro:macro>


  <!-- Macro that connects a cable to a UAV -->
  <xacro:macro name="cable_macro"
    params="robot_namespace uav_body_frame id_number">

    <!-- ################################################################### -->
    <!-- ##                             LINKS                             ## -->
    <!-- ################################################################### -->

    <!-- This sphere is between payload (root node) and cable -->
    <link name="${robot_namespace}/aux_pay_${id_number}">
      <xacro:sphere_macro r="${sphere_radius}" mass="${sphere_mass}"/>
      <!-- For TESTING purposes: 
      <xacro:cuboid_macro x="0.1" y="0.3" z="0.001" mass="1"/> -->
    </link>

    <!-- The CABLE is represented as a cylindrical link -->
    <link name="${robot_namespace}/cable_${id_number}">
      <inertial>
        <origin xyz="0 0 ${cable_length/2}" rpy="0 0 0"/>
        <mass value="${cable_mass}"/>
        <inertia
          ixx="0.0" ixy="0.0" ixz="0.0"
          iyy="${cable_mass * cable_length * cable_length / 3}" iyz="0.0"
          izz="${cable_mass * cable_length * cable_length / 3}"/>
      </inertial>
      <visual>
        <origin xyz="0 0 ${cable_length/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${cable_length}" radius="${cable_radius}"/>
        </geometry>
      </visual>
    </link>

    <!-- This sphere is between cable and uav -->
    <link name="${robot_namespace}/aux_uav_${id_number}">
      <xacro:sphere_macro r="${sphere_radius}" mass="${sphere_mass}"/>
    </link>

    <!-- ################################################################### -->
    <!-- ##                            JOINTS                             ## -->
    <!-- ################################################################### -->

    <!-- Joint between payload sphere and the cable -->
    <joint name="${robot_namespace}/joint_sph_cab_${id_number}" type="continuous">

      <!-- Placing the joint ref frame in the center of the sphere -->
      <origin xyz="0 0 0" rpy="0 0 0" />

      <!-- Axis in the CHILD REFERENCE FRAME around which the rotation happens -->
      <axis xyz="1 0 0" />

      <parent link="${robot_namespace}/aux_pay_${id_number}" />
      <child link="${robot_namespace}/cable_${id_number}" />

    </joint>


    <!-- Joint between the cable and the UAV sphere -->
    <joint name="${robot_namespace}/joint_cab_sph_${id_number}" type="continuous">

      <!-- Placing the joint ref frame on the upper end of the cable -->
      <origin xyz="0 0 ${cable_length}" rpy="0 0 0" />

      <!-- Axis in the CHILD REFERENCE FRAME around which the rotation happens -->
      <axis xyz="1 0 0" />

      <parent link="${robot_namespace}/cable_${id_number}" />
      <child link="${robot_namespace}/aux_uav_${id_number}" />

    </joint>


    <!-- Joint between the UAV sphere amd the UAV-->
    <joint name="${robot_namespace}/joint_sph_uav_${id_number}" type="continuous">

      <!-- Placing the joint ref frame in the center of the sphere -->
      <origin xyz="0 0 0" rpy="0 0 0" />

      <!-- Axis in the CHILD REFERENCE FRAME around which the rotation happens -->
      <axis xyz="0 1 0" />

      <parent link="${robot_namespace}/aux_uav_${id_number}" />
      <child link="${uav_body_frame}" />
    </joint>

  </xacro:macro>


  <xacro:macro name="payload_macro" params="link1 link2">

    <!-- This link represents the payload -->
    <link name="bar">
      <xacro:cuboid_macro x="${x_payload}" y="${y_payload}" z="${z_payload}" mass="${payload_mass}"/>
    </link>


    <!-- Joint connecting to the cable lifterd by the first UAV -->
    <joint name="bar/joint_sph1" type="continuous">

      <!-- Placing the joint reference frame on one end of the bar -->
      <origin xyz="${-x_payload/2} 0 ${z_payload/2 + sphere_radius}" rpy="0 0 0" />

      <!-- Axis in the CHILD REFERENCE FRAME around which the rotation happens -->
      <axis xyz="0 1 0" />

      <parent link="bar" />
      <child link="${link1}" />
    </joint>


    <!-- Joint connecting to the cable lifterd by the second UAV -->
    <joint name="bar/joint_sph2" type="continuous">

      <!-- Placing the joint reference frame on one end of the bar -->
      <origin xyz="${x_payload/2} 0 ${z_payload/2 + sphere_radius}" rpy="0 0 0" />

      <!-- Axis in the CHILD REFERENCE FRAME around which the rotation happens -->
      <axis xyz="0 1 0" />

      <parent link="bar" />
      <child link="${link2}" />
    </joint>

  </xacro:macro>

</robot>